pipeline: repvar-pipeline

api:
  small_api_key: fillers
  large_api_key: fillers 
  small_base_url: http://localhost:8082/v1
  large_base_url: http://localhost:8082/v1 
  small_model: Heralax/Augmentoolkit-DataSpecialist-v0.1
  large_model: Heralax/Augmentoolkit-DataSpecialist-v0.1
  small_mode: api
  large_mode: api
path:
  input_dir: ./inputs/strategic_culture
  output_dir: ./outputs/11nov-repvar
  prompts: generation/core_pipelines/representation_variation/prompts_local
  default_prompts: generation/core_pipelines/representation_variation/prompts
  prompts_inferred: generation/core_pipelines/representation_variation/prompts_inferred_facts_local
  default_prompts_inferred: generation/core_pipelines/representation_variation/prompts_inferred_facts
system:
  completion_mode: False
  concurrency_limit: 2
  use_stop: True
  subset_size: 30
  use_min_p: False
  use_subset: True 
  chunk_size: 1200
  keep_system_prompt: True
  variation_generator_count: 4 # higher = more variations! ideally even if the same prompt is selected more than once, the variations will still be significant.
  make_inferred_facts: True
dataset:
  dataset_context: China policy decision making and strategic culture
  include_context_in_dataset: True
  code_variation_functions: ["keyboard_augmentation"] # other options include: "allcaps" "lowercase" "serialkillercase" (which is LiKe ThIs) "titlecase" "sentencecase" "snakecase" "kebabcase" "camelcase" "pascalcase" "randomcase" "invertcase"
  additional_dataset_context: "" # added during generation of the data; optional
meta_datagen:
  do_meta_datagen: False
  meta_datagen_keys:
    - judgement_details
    - atomic_facts_details
    - variations_details
  meta_datagen_extras:
cost:
  cost_per_million_small_input: 0.07
  cost_per_million_small_output: 0.14
  cost_per_million_large_input: 0.23
  cost_per_million_large_output: 0.40
